services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    # 👇 Add these new settings
    deploy:
      resources:
        limits:
          memory: 1.5G # Increase memory limit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
    # 👇 Replace your current command with this:
    command: >
      gunicorn
      --timeout 180          # 3 min timeout (was 4360)
      --workers 2            # Reduce workers (was 3)
      --threads 2            # Add threads
      --worker-class gthread # Better for I/O
      --bind 0.0.0.0:8000
      --max-requests 500     # Auto-restart workers
      --preload              # Load app before forking
      core.wsgi:application
