services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Add these health checks

    # Add resource limits
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    # Optimized command
    command: >
      gunicorn --timeout 120
      --workers 4
      --threads 2
      --worker-class gthread
      --bind 0.0.0.0:8000
      --max-requests 1000
      --max-requests-jitter 50
      --access-logfile -
      --error-logfile -
      core.wsgi:application
