apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-auth
  template:
    metadata:
      labels:
        app: django-auth
    spec:
      containers:
        - name: django-auth
          image: your-dockerhub-username/django-auth:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
---
apiVersion: v1
kind: Service
metadata:
  name: django-auth-service
spec:
  selector:
    app: django-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
